site_name: ARTIGA AI for Real-Time Image Generation and Article Creation

repo_name: HarshVasisht/ARTIGA
repo_url: https://github.com/HarshVasisht/ARTIGA

theme:
  name: 'dracula'
  logo: assets/img/dracula.png
  nav_style: dark
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
    primary: '#BD93F9'
    accent: '#8BE9FD'
    text: '#F8F8F2'
    code: '#44475A'
    background: '#282A36'
    heading: '#6272A4'
    link: '#FF79C6'
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

nav:
  - Home: index.md
  - Real-Time Image Generation: image_generation.md
  - Article Creation with AI: article_creation.md
  - About Us: about.md

markdown_extensions:
  - admonition
  - toc:
      toc_depth: 3
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/HarshVasisht/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/HarshVasisht
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/HarshVasisht
    - icon: fontawesome/brands/google
      link: https://www.harsh.ai.in
